config/routes.rb
Rails.application.routes.draw do
  root  "site#index"
  get "/dashboard" , to: "site#index"
  get "/library" , to: "site#index"
  get "/library/:id" , to: "site#index"
  get "/channels" , to: "site#index"
  get "/settings" , to: "site#index"
  get "/users" , to: "site#index"
  get "/login" , to: "site#index"
  resources :settings

  get '/files' , to:"album#files"
  get '/albums' , to: "album#albums"
  get '/album/:id', to: 'album#one_album'
  get '/get-genres' , to: "settings#genres"
  get '/get-categories' , to: 'settings#categories'
  post '/add-library', to: 'album#add_album'
  post '/convert-video', to: 'album#convert_video'
  get '/loading' , to: "album#loading"
  get '/sample' , to: 'album#sample'
  delete '/remove-album' ,to: 'album#delete_album'
  #settings
  post 'add-genre' , to: 'settings#add_genre'
  delete 'delete-genre' ,to: 'settings#delete_genre'
  post 'add-category', to: 'settings#add_category'
  delete 'delete-category' , to: 'settings#delete_category'
  #users
  get 'all-users', to:'user#user_all'
  post 'create-user', to: 'user#create_user'
  delete 'delete-user', to: 'user#delete_user'
  put 'change-role' , to: 'user#change_role'
  get 'auth', to: 'user#login'
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  # GET /settings or /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1 or /settings/1.json
  def show
  end

  def genres
    genres = Genre.all.where('hide=1')
    render :json =>genres
  end

  def add_genre
    status  = params[:hide]
    name  = params[:name]
     Genre.create(name: name,hide: 1)
    render :json => {:name=>name , :status=>status}
  end

  def  delete_genre
    begin
      Genre.destroy(params[:id])
      render :json =>{:msg => 'Genre deleted'}
    rescue ActiveRecordError => err
      render :json => {:msg => err}
    end
  end

  def categories
    categories = Category.all
    render :json =>categories
  end

  def add_category
    Category.create(name:params[:name],paraent_id:1,hide: 1)
  end

  def delete_category
    begin
      Category.destroy(params[:id])
      render :json =>{:msg=> "Category deleted"}
    rescue ActiveRecordError => err
      render :json=>{:msg =>err}
    end
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings or /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: "Setting was successfully created." }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1 or /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to @setting, notice: "Setting was successfully updated." }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1 or /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url, notice: "Setting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def setting_params
      params.fetch(:setting, {})
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= form_with(model: setting) do |form| %>
  <% if setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
        <% setting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<h1>Editing Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>

app/views/settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Settings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= link_to 'Show', setting %></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_setting_path %>

app/views/settings/new.html.erb
<h1>New Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>